apiVersion: v1
kind: Service
metadata:
  name: web-backend-service
spec:
  type: NodePort
  selector:
    app: web-backend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000
